#!/usr/bin/env node
/**
 * Merge the two tagging passes and write the artefacts — packet 12.1, E007.
 *
 *   node audit/scripts/tag-merge.mjs
 *
 * Reads audit/runs/packet-12.1/pass1-tags.json and pass2-tags.json, writes:
 *   audit/runs/packet-12.1/tagging-diff.md          — agreement, pass-1-only, pass-2-only, per item
 *   audit/runs/packet-12.1/section_practice-tags.json — the agreed tags for the DB rows, STAGED
 *
 * Only tags BOTH passes produced are written. A tag one pass made alone is not a tag; it is a line
 * on the review list. See audit/EXAM-PRACTICE.md, "The independence rule".
 *
 * The section_practice half is a FILE, not a row. Rule 6: this packet may not write live content,
 * and `spec_items` does not exist as a column until a human runs scripts/packet-12-1-spec-items.sql.
 *
 * RETIRED FOR SECTION_PRACTICE BY PACKET 12.5, which deleted section_practice-tags.json. Neither the guard
 * nor any gate reads it; only packet 12.2's historical probe (audit/runs/packet-12.2/probe-items.mjs)
 * still names it, so re-run that probe against 94807d3 if it is ever needed. Instead, bank 2's tags now live in audit/practice-spec-items.json, keyed by item id,
 * for every section and both banks (audit/runs/packet-12.5/merge.mjs). Re-running this script
 * recreates the file as a historical record of packet 12.1's Market Failure pass; do not commit it.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const RUN = path.join(ROOT, 'audit/runs/packet-12.1');

const pass1 = JSON.parse(fs.readFileSync(path.join(RUN, 'pass1-tags.json'), 'utf8'));
const pass2 = JSON.parse(fs.readFileSync(path.join(RUN, 'pass2-tags.json'), 'utf8'));
const oracle = JSON.parse(fs.readFileSync(path.join(ROOT, 'audit/raw/spec-items.json'), 'utf8'));
const BANKS = {
  'section_practice.live': {
    file: 'audit/content-sections/economics__market-failure.json',
    what: 't=0 dump — what a student is served until the packet 5/7 ship checkpoint',
  },
  'section_practice.staged': {
    file: 'audit/snapshots/packet-25-bundle__economics__market-failure.json',
    what: 'packet 25 rebuild — what publishing the section would serve',
  },
};
const bankRows = Object.fromEntries(
  Object.entries(BANKS).map(([k, b]) => {
    const j = JSON.parse(fs.readFileSync(path.join(ROOT, b.file), 'utf8'));
    return [k, j.practice || j.tables?.practice || []];
  }),
);

const { subject, topic } = pass1;
const leaves = oracle.items.filter((r) => r.subject === subject && r.topic === topic && r.kind === 'leaf');
const leafIds = leaves.map((r) => r.id);

const keys = [...new Set([...Object.keys(pass1.tags), ...Object.keys(pass2)])].sort();
const rows = keys.map((key) => {
  const a = new Set(pass1.tags[key] || []);
  const b = new Set(pass2[key] || []);
  return {
    key,
    agreed: [...a].filter((id) => b.has(id)).sort(),
    onlyPass1: [...a].filter((id) => !b.has(id)).sort(),
    onlyPass2: [...b].filter((id) => !a.has(id)).sort(),
  };
});

const examined = new Set(rows.flatMap((r) => r.agreed));
const unexamined = leafIds.filter((id) => !examined.has(id));
const pct = ((examined.size / leafIds.length) * 100).toFixed(1);

/* ── tagging-diff.md ─────────────────────────────────────────────────────────────────────────── */

const totalAgreed = rows.reduce((n, r) => n + r.agreed.length, 0);
const total1 = rows.reduce((n, r) => n + r.agreed.length + r.onlyPass1.length, 0);
const total2 = rows.reduce((n, r) => n + r.agreed.length + r.onlyPass2.length, 0);

const md = [];
md.push(`# Two-pass tagging — ${subject} ${topic} (Market Failure)`);
md.push('');
md.push('Packet 12.1, E007. Generated by `node audit/scripts/tag-merge.mjs`; do not edit by hand.');
md.push('');
md.push('**Pass 1** — the packet author, reading each question\'s TEXT ONLY against the topic\'s rows of');
md.push('`audit/raw/spec-items.json`. Recorded in `pass1-tags.json` before pass 2 ran.');
md.push('');
md.push('**Pass 2** — `audit/scripts/tag-lexical.mjs`, a deterministic lexical matcher whose only inputs');
md.push('are the question text and the oracle rows. It never sees pass 1. Its rule is fixed in the file');
md.push('header and was not tuned after its output was read.');
md.push('');
md.push('**Only agreed tags are written.** A tag one pass made alone is on the review list below.');
md.push('');
md.push('| | count |');
md.push('|---|---|');
md.push(`| questions tagged | ${rows.length} |`);
md.push(`| tags proposed by pass 1 | ${total1} |`);
md.push(`| tags proposed by pass 2 | ${total2} |`);
md.push(`| **agreed, and therefore written** | **${totalAgreed}** |`);
md.push(`| distinct leaves examined by agreed tags | ${examined.size} of ${leafIds.length} (${pct}%) |`);
md.push('');
md.push('## Per question');
md.push('');
for (const r of rows) {
  md.push(`### \`${r.key}\``);
  md.push('');
  md.push(`- agreed: ${r.agreed.length ? r.agreed.map((i) => `\`${i}\``).join(', ') : '**none — left untagged**'}`);
  if (r.onlyPass1.length) md.push(`- pass 1 only (review): ${r.onlyPass1.map((i) => `\`${i}\``).join(', ')}`);
  if (r.onlyPass2.length) md.push(`- pass 2 only (review): ${r.onlyPass2.map((i) => `\`${i}\``).join(', ')}`);
  md.push('');
}
md.push('## Leaves with no agreed tag');
md.push('');
md.push(`${unexamined.length} of ${leafIds.length} leaves in ${topic} are examined by no question in either bank:`);
md.push('');
for (const id of unexamined) {
  const row = leaves.find((r) => r.id === id);
  md.push(`- \`${id}\` — ${row.wording}`);
}
md.push('');
md.push('## What the disagreements say');
md.push('');
md.push('The two passes disagree in one direction more than the other, and it is worth naming which.');
md.push('Pass 2 is lexical: it cannot tag a question that examines a leaf in different words, so every');
md.push('question whose wording avoids the specification\'s own vocabulary comes back empty from it.');
md.push(`That is why ${rows.filter((r) => !r.agreed.length).length} of the ${rows.length} questions carry no agreed tag and stay untagged rather than being credited`);
md.push('to a leaf on one pass\'s word. An untagged question is visible to `npm run spec-coverage`; a');
md.push('wrongly tagged one is not, and would inflate the coverage number permanently.');
md.push('');
fs.writeFileSync(path.join(RUN, 'tagging-diff.md'), `${md.join('\n')}\n`);

/* ── section_practice-tags.json ──────────────────────────────────────────────────────────────── */

const staged = {
  note: 'STAGED, NOT WRITTEN. Packet 12.1, E007, rule 6: this packet may not write live content, and section_practice has no spec_items column until a human runs scripts/packet-12-1-spec-items.sql. Only tags BOTH passes agreed on are here. A question absent from `rows` has no agreed tag and must stay untagged (NULL), not tagged as empty.',
  generated: new Date().toISOString().slice(0, 10),
  section: 'market-failure',
  subject,
  topic,
  matchBy: 'question text, exact — section_practice rows carry no stable item id in the t=0 dump',
  banks: Object.fromEntries(Object.entries(BANKS).map(([k, b]) => [k, b.what])),
  rows: rows
    .filter((r) => r.key.split(':')[0] in BANKS && r.agreed.length)
    .map((r) => {
      const [bank, idx] = r.key.split(':');
      const q = bankRows[bank][Number(idx)];
      return { bank, practiceIndex: Number(idx), question: q.question, command: q.command, marks: q.marks, spec_items: r.agreed };
    }),
  untagged: rows
    .filter((r) => r.key.split(':')[0] in BANKS && !r.agreed.length)
    .map((r) => {
      const [bank, idx] = r.key.split(':');
      return { bank, practiceIndex: Number(idx), question: bankRows[bank][Number(idx)].question };
    }),
};
fs.writeFileSync(path.join(RUN, 'section_practice-tags.json'), `${JSON.stringify(staged, null, 2)}\n`);

console.log(`agreed tags: ${totalAgreed} (pass 1 proposed ${total1}, pass 2 proposed ${total2})`);
console.log(`leaves examined: ${examined.size} of ${leafIds.length} (${pct}%)`);
console.log(`model-answer tags to write: ${JSON.stringify(Object.fromEntries(rows.filter((r) => r.key.startsWith('modelAnswers:') && r.agreed.length).map((r) => [r.key.split(':')[1], r.agreed])))}`);
console.log('wrote tagging-diff.md and section_practice-tags.json');
