import { money, FIRMS } from '../format.mjs';

/**
 * Expected values on a simple decision tree. Edexcel IAL Business, WBS13 (Unit 3), spec 3.3.3
 * Decision-making techniques, topic 3 "Decision trees" leaves a and b: "Construct and interpret
 * simple decision-tree diagrams" and "Calculations and interpretations of figures generated by
 * these techniques" (bus_spec.txt:1146, :1162-1164). Quantitative skills QS1 (an expected value is
 * a probability-weighted average) and QS8, "Use and interpret quantitative and non-quantitative
 * information in order to make decisions" (bus_spec.txt:2267, :2287).
 *
 * The tree is described in words rather than drawn: this drill is the arithmetic at the chance
 * nodes and the decision node, not the drawing. Two options, each with a cost and two outcomes
 * whose probabilities sum to 1. Step one is option A's expected value before its cost, step two
 * takes the cost off, step three does both for option B at once, and the last step is the
 * decision. The cost is where the marks go: the option with the higher expected value before its
 * cost is not always the one to choose, and a student who compares the gross figures is told so.
 *
 * ── Why no answer can be a figure on the card ──
 *
 * Every printed amount — each outcome and each cost — is a multiple of $5,000, and every answer is
 * drawn NOT to be: an expected value is a multiple of $500 (probabilities in steps of 0.05, outcomes
 * in $10,000s), and draws where it lands on a $5,000 multiple are refused, which carries over to the
 * net figures because the costs are $5,000 multiples too. So no answer can equal any printed figure
 * in either option, by construction rather than by a check that has to know which figures to look
 * at — and, as a consequence, the two options' refusals are independent of each other, which is
 * what lets `variants` be counted exactly.
 *
 * Probabilities of 0.5 are excluded: at 0.5 the expected value IS the average of the two outcomes,
 * which is the named slip for ignoring the probabilities.
 */

const PROBS = [];                                   // probability of the better outcome, in %
for (let p = 10; p <= 90; p += 5) if (p !== 50) PROBS.push(p);
const HIGH = { min: 50000, max: 250000, step: 10000 };
const LOW_MIN = 10000;                              // the worse outcome: $10,000 up to $20,000 below the better
const COST = { min: 10000, max: 90000, step: 5000 };
const FLOOR = -25000;                               // no option is expected to lose more than this
const MARGIN = 2000;                                // the decision is never closer than this
const MAX_GAP = 30000;                              // … nor further apart than this: see pairOk

const ev = (p, high, low) => (p * high + (100 - p) * low) / 100;
const prob = (p) => String(p / 100);

/** Every option the grid allows, in the order the draw would meet them. */
function* options() {
  for (const p of PROBS)
    for (let high = HIGH.min; high <= HIGH.max; high += HIGH.step)
      for (let low = LOW_MIN; low <= high - 20000; low += 10000)
        for (let cost = COST.min; cost <= COST.max; cost += COST.step) yield { p, high, low, cost };
}

const distinct = (values) => values.every((v, i) => values.every((w, j) => i === j || Math.abs(v - w) > 1));

/** Wrong methods for option A's two steps. */
const slipsA = ({ p, high, low, cost }) => ({
  ev: [(high + low) / 2, (p * high) / 100, ev(100 - p, high, low)],
  net: [ev(p, high, low), ev(p, high - cost, low)],
});
/** Wrong methods for option B's one step, which takes the cost off in the same breath. */
const slipsB = ({ p, high, low, cost }) => [ev(p, high, low), (high + low) / 2 - cost, (p * high) / 100 - cost];

/** Refusals that read one option only. Every slip is a whole number of dollars, so "further than
 *  the tolerance of 0.5" is "not equal", and two slips must not be equal either. */
function commonOk(o) {
  const value = ev(o.p, o.high, o.low);
  if (value % 5000 === 0) return false;           // see the note above
  return value - o.cost >= FLOOR;
}
function optionAOk(o) {
  if (!commonOk(o)) return false;
  const value = ev(o.p, o.high, o.low);
  const s = slipsA(o);
  return distinct([value, ...s.ev]) && distinct([value - o.cost, ...s.net]);
}
function optionBOk(o) {
  if (!commonOk(o)) return false;
  return distinct([ev(o.p, o.high, o.low) - o.cost, ...slipsB(o)]);
}

/**
 * The pair: a decision that is clear but not obvious, and at least one option worth taking. The
 * first version had no upper bound, and the two net figures were often $100,000 apart — the
 * decision could be read off the outcomes without any arithmetic, and the case this item exists
 * for, where the cost reverses the order, came up in only 682 draws of 5,000.
 */
const pairOk = (netA, netB) => {
  const gap = Math.abs(netA - netB);
  return gap >= MARGIN && gap <= MAX_GAP && Math.max(netA, netB) > 0;
};

/**
 * Counted by exhaustion: every valid option A against every valid option B, the pairs counted by
 * binary search over B's sorted net values rather than one by one (3.4 × 10⁹ pairs).
 * `node --input-type=module -e "import { countVariants } from
 * './lib/quant/templates/decision-tree.mjs'; console.log(countVariants())"`. Re-run after any change
 * to the draw and copy the result into `variants`.
 */
export function countVariants() {
  const netsB = [];
  for (const o of options()) if (optionBOk(o)) netsB.push(ev(o.p, o.high, o.low) - o.cost);
  netsB.sort((a, b) => a - b);
  // How many of B's net values are <= x.
  const upTo = (x) => { let lo = 0, hi = netsB.length; while (lo < hi) { const m = (lo + hi) >> 1; if (netsB[m] <= x) lo = m + 1; else hi = m; } return lo; };
  // How many are in [from, to], both ends included; B's values are whole dollars.
  const between = (from, to) => (to < from ? 0 : upTo(to) - upTo(from - 1));
  let n = 0;
  for (const o of options()) {
    if (!optionAOk(o)) continue;
    const netA = ev(o.p, o.high, o.low) - o.cost;
    // B below A: the decision is A, which must be worth taking.
    if (netA > 0) n += between(netA - MAX_GAP, netA - MARGIN);
    // B above A: the decision is B, which must be worth taking.
    n += between(Math.max(netA + MARGIN, 1), netA + MAX_GAP);
  }
  return n * FIRMS.length;
}

function drawOption(rng) {
  const p = rng.pick(PROBS);
  const high = rng.step(HIGH.min, HIGH.max, HIGH.step);
  const low = rng.step(LOW_MIN, high - 20000, 10000);
  const cost = rng.step(COST.min, COST.max, COST.step);
  return { p, high, low, cost };
}

const template = {
  id: 'decision-tree',
  subject: 'business',
  unit: 'WBS13',
  specCode: '3.3.3',
  specLeaf: '3.3.3 · 3a, 3b',
  qs: 'QS1, QS8',
  specTerm: 'decision tree',
  title: 'Decision trees: expected values',
  topic: 'Decision-making techniques',
  // Counted, not multiplied out: 74,256 options on the grid for each of A and B (57,859 and 58,210
  // of them pass their own tests), every valid pairing that pairOk accepts, × 7 firms.
  variants: 6203818404,

  draw(rng) {
    // About one attempt in 6.5 is kept (20,000 seeds measured; the worst took 67), so the bound
    // is set well clear of it.
    for (let attempt = 0; attempt < 400; attempt++) {
      const a = drawOption(rng);
      const b = drawOption(rng);
      if (!optionAOk(a) || !optionBOk(b)) continue;
      const netA = ev(a.p, a.high, a.low) - a.cost;
      const netB = ev(b.p, b.high, b.low) - b.cost;
      if (!pairOk(netA, netB)) continue;
      return { firm: rng.pick(FIRMS), a, b, evA: ev(a.p, a.high, a.low), evB: ev(b.p, b.high, b.low), netA, netB };
    }
    throw new Error('decision-tree: no clean draw in 400 attempts');
  },

  /** Checked independently by audit/scripts/quant-check.mjs on every draw. */
  invariants(d) {
    const bad = [];
    for (const [name, o, value] of [['A', d.a, d.evA], ['B', d.b, d.evB]]) {
      if (Math.abs(o.p / 100 + (100 - o.p) / 100 - 1) > 1e-9) bad.push(`option ${name}'s probabilities do not sum to 1`);
      if (o.p === 50) bad.push(`option ${name} has probabilities of 0.5, where the average of the outcomes is the answer`);
      if (!(o.high > o.low)) bad.push(`option ${name}'s outcomes are not in order`);
      if (!Number.isInteger(value)) bad.push(`option ${name}'s expected value is not a whole number of dollars`);
      if (value % 5000 === 0) bad.push(`option ${name}'s expected value is a $5,000 multiple, the grid every printed figure sits on`);
      if ([o.high, o.low, o.cost].some((f) => f % 5000 !== 0)) bad.push(`option ${name} prints a figure off the $5,000 grid`);
    }
    if (d.evA - d.a.cost !== d.netA || d.evB - d.b.cost !== d.netB) bad.push('a net figure is not expected value minus cost');
    if (Math.abs(d.netA - d.netB) < MARGIN) bad.push('the two options are too close for the decision to mean anything');
    if (Math.abs(d.netA - d.netB) > MAX_GAP) bad.push('the two options are so far apart that the decision needs no arithmetic');
    if (Math.max(d.netA, d.netB) <= 0) bad.push('neither option is worth taking, so the choice has no right answer');
    return bad;
  },

  build(d) {
    const { a, b } = d;
    const sa = slipsA(a);
    const sb = slipsB(b);
    const pickA = d.netA > d.netB;
    const grossDisagrees = (d.evA > d.evB) !== pickA;
    const describe = (name, o) =>
      `**Option ${name}** costs **${money(o.cost)}**: there is a **${prob(o.p)}** probability that it earns ` +
      `**${money(o.high)}** and a **${prob(100 - o.p)}** probability that it earns **${money(o.low)}**.`;
    return {
      stem: `**${d.firm}** is choosing between two options. ${describe('A', a)} ${describe('B', b)}`,
      steps: [
        {
          id: 'evA',
          label: 'Expected value of option A, before its cost',
          method: '(probability × outcome) + (probability × outcome)',
          prefix: '$',
          marks: 1,
          dp: 0,
          answer: d.evA,
          tolerance: 0.5,
          slips: [
            { value: sa.ev[0], note: 'That is the plain average of the two outcomes. Weight each outcome by its probability instead.' },
            { value: sa.ev[1], note: 'You left out the second outcome. Every branch counts: add its probability × outcome too.' },
            { value: sa.ev[2], note: 'You swapped the probabilities. Each outcome is multiplied by its own probability.' },
          ],
        },
        {
          id: 'netA',
          label: 'Net expected value of option A, after its cost',
          method: 'expected value − cost of the option',
          prefix: '$',
          marks: 1,
          dp: 0,
          answer: d.netA,
          tolerance: 0.5,
          ofr: (v) => (Number.isFinite(v.evA) ? v.evA - a.cost : null),
          slips: [
            { value: sa.net[0], note: 'That is the expected value before the cost. Take the cost of the option off it.' },
            { value: sa.net[1], note: 'You took the cost off one outcome only. The cost is paid whichever outcome happens, so it comes off the whole expected value.' },
          ],
        },
        {
          id: 'netB',
          label: 'Net expected value of option B, after its cost',
          method: '(probability × outcome) + (probability × outcome) − cost of the option',
          prefix: '$',
          marks: 2,
          dp: 0,
          answer: d.netB,
          tolerance: 0.5,
          slips: [
            { value: sb[0], note: 'That is the expected value before the cost. Take the cost of option B off it.' },
            { value: sb[1], note: 'You averaged the two outcomes. Weight each one by its probability before taking the cost off.' },
            { value: sb[2], note: 'You left out the second outcome. Add its probability × outcome before taking the cost off.' },
          ],
        },
        {
          id: 'verdict',
          label: 'On expected values alone, the business should choose',
          method: 'the option with the higher net expected value',
          type: 'choice',
          marks: 1,
          choices: ['Option A', 'Option B'],
          answer: pickA ? 'Option A' : 'Option B',
          correctNote:
            `Option ${pickA ? 'A' : 'B'} is expected to be worth ${money(pickA ? d.netA : d.netB)} after its cost, ` +
            `against ${money(pickA ? d.netB : d.netA)} for option ${pickA ? 'B' : 'A'}.` +
            (grossDisagrees ? ` Before costs option ${pickA ? 'B' : 'A'} looked better — the cost is what decides it.` : ''),
          wrongNote:
            `Compare the NET figures: option A ${money(d.netA)}, option B ${money(d.netB)}.` +
            (grossDisagrees ? ` Before costs the order is the other way round, which is why the cost has to come off first.` : ''),
        },
      ],
      solution: [
        `Option A: ${prob(a.p)} × ${money(a.high)} + ${prob(100 - a.p)} × ${money(a.low)} = **${money(d.evA)}**`,
        `Option A after its cost: ${money(d.evA)} − ${money(a.cost)} = **${money(d.netA)}**`,
        `Option B: ${prob(b.p)} × ${money(b.high)} + ${prob(100 - b.p)} × ${money(b.low)} − ${money(b.cost)} = ${money(d.evB)} − ${money(b.cost)} = **${money(d.netB)}**`,
        `Option ${pickA ? 'A' : 'B'} has the higher net expected value, so on expected values alone the business should choose **option ${pickA ? 'A' : 'B'}**`,
      ],
    };
  },
};

export default template;
