import { money, FIRMS } from '../format.mjs';

/**
 * Net present value from printed discount factors. Edexcel IAL Business, WBS13 (Unit 3), spec
 * 3.3.3 Decision-making techniques, topic 2 leaves c and d: "Discounted cash flow (net present
 * value only)" and "Calculations and interpretations of figures generated by these techniques"
 * (bus_spec.txt:1146, :1158-1160). Quantitative skill QS6, "Calculate investment appraisal
 * outcomes and interpret results" (bus_spec.txt:2281) — IA2 only, which is why this is a Unit 3
 * drill beside `payback` and `arr`.
 *
 * ── Why the discount factors are printed ──
 *
 * An IAL paper supplies them: the specification asks for net present value, not for deriving a
 * factor from a rate, and a student who is made to compute 1 ÷ 1.1³ is being drilled on a skill
 * the exam never asks for. The factors below are the three-decimal-place values the published
 * tables use (1 ÷ (1 + r)ⁿ, rounded), held as whole thousandths so that no present value is ever
 * a floating-point product: every cash flow is a multiple of $1,000, so `cash flow × factor` is
 * `(cash flow ÷ 1,000) × thousandths`, a whole number of dollars, exactly.
 *
 * ── Why the investment is drawn last ──
 *
 * Drawn backwards from the answer, like `arr`. The cash flows and the rate fix the total present
 * value; the investment is then a multiple of $5,000 within 20% of it either way, so the NPV
 * comes out positive about as often as negative and is never an implausible fraction of the
 * outlay. A draw whose NPV is within $1,000 of zero is refused: the verdict step would be judging
 * a rounding, and at zero the "wrong way round" slip on the NPV step would BE the answer.
 */

/** Discount factors in thousandths, years 1-3. `invariants` re-derives every one from the rate. */
const FACTORS = {
  5: [952, 907, 864],
  6: [943, 890, 840],
  8: [926, 857, 794],
  10: [909, 826, 751],
  12: [893, 797, 712],
  15: [870, 756, 658],
};
const RATES = Object.keys(FACTORS).map(Number);

/** Net cash inflow in each year, in dollars. */
const FLOW = { min: 10000, max: 40000, step: 1000 };
const OUTLAY_STEP = 5000;

const factor = (thousandths) => (thousandths / 1000).toFixed(3);

/** Present values of the three inflows, exact: the flow is a multiple of 1,000. */
const presentValues = (rate, flows) => flows.map((cf, i) => (cf / 1000) * FACTORS[rate][i]);

/** The investments the draw may choose for a given total present value: $5,000 steps, ±20%. */
function outlayWindow(totalPV) {
  return {
    lo: Math.ceil((4 * totalPV) / (5 * OUTLAY_STEP)) * OUTLAY_STEP,
    hi: Math.floor((6 * totalPV) / (5 * OUTLAY_STEP)) * OUTLAY_STEP,
  };
}

/**
 * Everything the card prints and asks, or null when the draw must be refused. One function, used
 * by `draw` to reject and by `countVariants` to count, so the declared variety cannot drift from
 * what the draw can actually reach.
 */
function derive(rate, flows, investment) {
  const pvs = presentValues(rate, flows);
  const totalPV = pvs[0] + pvs[1] + pvs[2];
  const npv = totalPV - investment;
  if (Math.abs(npv) < 1000) return null;

  /*
   * No answer may be a figure printed above it. The NPV is a whole number of dollars and every
   * cash flow is a whole thousand, so an NPV of exactly $12,000 beside a $12,000 inflow would
   * mark a student correct for copying it. The magnitude is checked too: a negative NPV whose
   * size is printed on the card is one minus sign away from a free mark.
   */
  const printed = [investment, ...flows];
  if ([pvs[2], totalPV, npv, Math.abs(npv)].some((answer) => printed.includes(answer))) return null;

  /*
   * Two named wrong methods on one step must not land on the same figure, or the feedback names
   * the wrong one. Only one pair can meet: the undiscounted NPV equals the reversed NPV when the
   * investment is exactly halfway between the raw inflows and their present value.
   */
  const sumFlows = flows[0] + flows[1] + flows[2];
  if (Math.abs((sumFlows - investment) - (investment - totalPV)) <= 1) return null;

  return { rate, flows, investment, pvs, totalPV, npv, sumFlows };
}

/**
 * The number of distinct stems the draw can produce, counted by exhaustion over the same grid and
 * the same `derive`: `node --input-type=module -e "import { countVariants } from
 * './lib/quant/templates/npv.mjs'; console.log(countVariants())"`. Re-run it after any change to
 * the draw and copy the result into `variants` — `quant-check` reads that number.
 */
export function countVariants() {
  let n = 0;
  for (const rate of RATES)
    for (let a = FLOW.min; a <= FLOW.max; a += FLOW.step)
      for (let b = FLOW.min; b <= FLOW.max; b += FLOW.step)
        for (let c = FLOW.min; c <= FLOW.max; c += FLOW.step) {
          const flows = [a, b, c];
          const pvs = presentValues(rate, flows);
          const { lo, hi } = outlayWindow(pvs[0] + pvs[1] + pvs[2]);
          for (let investment = lo; investment <= hi; investment += OUTLAY_STEP) {
            if (derive(rate, flows, investment)) n++;
          }
        }
  return n * FIRMS.length;
}

const template = {
  id: 'npv',
  subject: 'business',
  unit: 'WBS13',
  specCode: '3.3.3',
  specLeaf: '3.3.3 · 2c, 2d',
  qs: 'QS6',
  specTerm: 'net present value',
  title: 'Net present value',
  topic: 'Decision-making techniques',
  // Counted, not multiplied out: 6 rates × 31³ cash-flow sets × the $5,000 investments within
  // ±20% of each total present value, less the refusals in `derive`, × 7 firms. See countVariants.
  variants: 5814305,

  draw(rng) {
    for (let attempt = 0; attempt < 200; attempt++) {
      const rate = rng.pick(RATES);
      const flows = [0, 1, 2].map(() => rng.step(FLOW.min, FLOW.max, FLOW.step));
      const pvs = presentValues(rate, flows);
      const { lo, hi } = outlayWindow(pvs[0] + pvs[1] + pvs[2]);
      const d = derive(rate, flows, rng.step(lo, hi, OUTLAY_STEP));
      if (d) return { firm: rng.pick(FIRMS), ...d };
    }
    throw new Error('npv: no clean draw in 200 attempts');
  },

  /** Checked independently by audit/scripts/quant-check.mjs on every draw. */
  invariants(d) {
    const bad = [];
    const r = d.rate / 100;
    FACTORS[d.rate].forEach((f, i) => {
      if (f !== Math.round(1000 / (1 + r) ** (i + 1))) bad.push(`the year ${i + 1} factor is not 1 ÷ (1 + r)^n to 3 dp`);
    });
    d.pvs.forEach((pv, i) => {
      if (!Number.isInteger(pv)) bad.push(`the year ${i + 1} present value is not a whole number of dollars`);
    });
    if (d.pvs.reduce((a, b) => a + b, 0) !== d.totalPV) bad.push('the present values do not sum to the total');
    if (d.totalPV - d.investment !== d.npv) bad.push('NPV is not total present value minus the investment');
    if (Math.abs(d.npv) < 1000) bad.push('NPV is within $1,000 of zero, so the verdict is judging a rounding');
    if (d.investment % OUTLAY_STEP !== 0) bad.push('the investment is not a round figure');
    if ([d.pvs[2], d.totalPV, d.npv, Math.abs(d.npv)].some((a) => [d.investment, ...d.flows].includes(a))) {
      bad.push('an answer is one of the figures printed in the stem');
    }
    return bad;
  },

  build(d) {
    const [f1, f2, f3] = FACTORS[d.rate];
    const [cf1, cf2, cf3] = d.flows;
    const worthwhile = d.npv > 0;
    const others = d.pvs[0] + d.pvs[1];
    return {
      stem:
        `**${d.firm}** is considering an investment of **${money(d.investment)}** in new equipment. It ` +
        `expects net cash inflows of **${money(cf1)}** in year 1, **${money(cf2)}** in year 2 and ` +
        `**${money(cf3)}** in year 3. At a discount rate of **${d.rate}%** the discount factors are ` +
        `**${factor(f1)}** for year 1, **${factor(f2)}** for year 2 and **${factor(f3)}** for year 3.`,
      steps: [
        {
          id: 'presentValue',
          label: 'Present value of the year 3 net cash inflow',
          method: 'net cash inflow × that year’s discount factor',
          prefix: '$',
          marks: 1,
          dp: 0,
          answer: d.pvs[2],
          tolerance: 0.5,
          slips: [
            { value: cf3, note: 'That is the cash flow before discounting. Multiply it by the year 3 discount factor.' },
            { value: cf3 / (f3 / 1000), note: 'You divided by the discount factor. A present value is the cash flow multiplied by it, so it is always smaller.' },
            { value: (cf3 / 1000) * f1, note: 'You used the year 1 discount factor. Each year’s cash flow takes the factor printed for its own year.' },
          ],
        },
        {
          id: 'totalPV',
          label: 'Total present value of the three years’ inflows',
          method: 'the sum of each year’s net cash inflow × its discount factor',
          prefix: '$',
          marks: 1,
          dp: 0,
          answer: d.totalPV,
          tolerance: 0.5,
          ofr: (v) => (Number.isFinite(v.presentValue) ? others + v.presentValue : null),
          slips: [
            { value: d.sumFlows, note: 'You added the cash flows before discounting them. Discount each year first, then add the present values.' },
          ],
        },
        {
          id: 'npv',
          label: 'Net present value',
          method: 'total present value − the initial investment',
          prefix: '$',
          marks: 2,
          dp: 0,
          answer: d.npv,
          tolerance: 0.5,
          ofr: (v) => (Number.isFinite(v.totalPV) ? v.totalPV - d.investment : null),
          slips: [
            { value: d.totalPV, note: 'That is the total present value. The initial investment has to come off it to leave the net present value.' },
            { value: d.sumFlows - d.investment, note: 'You took the investment off cash flows that were never discounted. NPV uses the present values, not the raw inflows.' },
            { value: -d.npv, note: 'Right size, wrong way round. NPV is the present value of the inflows minus the investment, not the other way.' },
          ],
        },
        {
          id: 'verdict',
          label: 'On financial grounds alone, the investment is',
          method: 'a positive NPV means the discounted inflows are worth more than the outlay today',
          type: 'choice',
          marks: 1,
          choices: ['Worthwhile', 'Not worthwhile'],
          answer: worthwhile ? 'Worthwhile' : 'Not worthwhile',
          correctNote: worthwhile
            ? `The NPV is positive: discounted at ${d.rate}%, the inflows are worth ${money(d.totalPV)} today against an outlay of ${money(d.investment)}.`
            : `The NPV is negative: discounted at ${d.rate}%, the inflows are worth only ${money(d.totalPV)} today against an outlay of ${money(d.investment)}.`,
          wrongNote: worthwhile
            ? `Look at the sign of the NPV. It is positive (${money(d.npv)}), so the discounted inflows more than cover the outlay.`
            : d.sumFlows > d.investment
              ? `Look at the sign of the NPV. It is negative (${money(d.npv)}): the inflows add up to more than the outlay, but their present value does not.`
              : `Look at the sign of the NPV. It is negative (${money(d.npv)}), so the discounted inflows do not cover the outlay.`,
        },
      ],
      solution: [
        `Year 1: ${money(cf1)} × ${factor(f1)} = ${money(d.pvs[0])}`,
        `Year 2: ${money(cf2)} × ${factor(f2)} = ${money(d.pvs[1])}`,
        `Year 3: ${money(cf3)} × ${factor(f3)} = **${money(d.pvs[2])}**`,
        `Total present value = ${money(d.pvs[0])} + ${money(d.pvs[1])} + ${money(d.pvs[2])} = **${money(d.totalPV)}**`,
        `NPV = ${money(d.totalPV)} − ${money(d.investment)} = **${money(d.npv)}**`,
        `The NPV is ${worthwhile ? 'positive' : 'negative'}, so on financial grounds the investment is **${worthwhile ? 'worthwhile' : 'not worthwhile'}**`,
      ],
    };
  },
};

export default template;
