// Topic Linkage Map — Node & Edge data for Edexcel IAL Economics
// Categories map to CSS accent variables for automatic light/dark theme support

export const CATEGORIES = {
  // Unit 1 categories
  foundation: { label: 'Foundation', color: '#FBBF24', cssVar: '--accent-amber' },
  market:     { label: 'Market Mechanism', color: '#10B981', cssVar: '--accent-green-light' },
  elasticity: { label: 'Elasticity', color: '#38BDF8', cssVar: '--accent-blue' },
  welfare:    { label: 'Welfare & Taxes', color: '#C084FC', cssVar: '--accent-indigo' },
  failure:    { label: 'Market Failure', color: '#F87171', cssVar: '--accent-red-light' },
  policy:     { label: 'Policy', color: '#FB923C', cssVar: '--accent-amber' },
  // Unit 2 categories
  measure:    { label: 'Economic Measures', color: '#FBBF24', cssVar: '--accent-amber' },
  ad:         { label: 'Aggregate Demand', color: '#34D399', cssVar: '--accent-green-light' },
  as:         { label: 'Aggregate Supply', color: '#38BDF8', cssVar: '--accent-blue' },
  income:     { label: 'National Income & Growth', color: '#C084FC', cssVar: '--accent-indigo' },
  conflict:   { label: 'Objectives & Conflicts', color: '#F87171', cssVar: '--accent-red-light' },
};

export const UNIT_1 = {
  viewBox: { w: 820, h: 640 },
  nodes: [
    { id: 'scarcity',   label: 'Scarcity &\nOpp. Cost',       x: 420, y: 55,  category: 'foundation', full: 'Scarcity & Opportunity Cost' },
    { id: 'ppf',        label: 'PPF',                         x: 210, y: 135, category: 'foundation', full: 'Production Possibility Frontiers' },
    { id: 'spec',       label: 'Specialisation\n& Money',     x: 635, y: 135, category: 'foundation', full: 'Specialisation & Money' },
    { id: 'price_mech', label: 'Price\nMechanism',            x: 420, y: 135, category: 'market',     full: 'The Price Mechanism' },
    { id: 'cons_beh',   label: 'Consumer\nBehaviour',         x: 115, y: 225, category: 'market',     full: 'Consumer Behaviour & Rationality' },
    { id: 'demand',     label: 'Demand\nCurve',               x: 295, y: 225, category: 'market',     full: 'The Demand Curve' },
    { id: 'supply',     label: 'Supply\nCurve',               x: 545, y: 225, category: 'market',     full: 'The Supply Curve' },
    { id: 'pes',        label: 'PES',                         x: 730, y: 225, category: 'elasticity', full: 'Price Elasticity of Supply' },
    { id: 'ped',        label: 'PED/YED\n/XED',               x: 165, y: 315, category: 'elasticity', full: 'Price, Income & Cross Elasticities' },
    { id: 'price_det',  label: 'Price\nDetermination',        x: 420, y: 315, category: 'market',     full: 'Price Determination & Equilibrium' },
    { id: 'taxes',      label: 'Taxes &\nSubsidies',          x: 685, y: 315, category: 'welfare',    full: 'Indirect Taxes & Subsidies' },
    { id: 'surplus',    label: 'C/P\nSurplus',                x: 275, y: 405, category: 'welfare',    full: 'Consumer & Producer Surplus' },
    { id: 'mkt_fail',   label: 'Market\nFailure',             x: 580, y: 405, category: 'failure',    full: 'Market Failure (all sources)' },
    { id: 'ext',        label: 'External-\nities',            x: 65,  y: 495, category: 'failure',    full: 'Positive & Negative Externalities' },
    { id: 'pub_goods',  label: 'Public\nGoods',               x: 215, y: 495, category: 'failure',    full: 'Non-Provision of Public Goods' },
    { id: 'info_fail',  label: 'Info\nFailure',               x: 390, y: 495, category: 'failure',    full: 'Imperfect Market Information' },
    { id: 'moral_haz',  label: 'Moral\nHazard',               x: 570, y: 495, category: 'failure',    full: 'Moral Hazard' },
    { id: 'bubbles',    label: 'Market\nBubbles',             x: 750, y: 495, category: 'failure',    full: 'Speculation & Market Bubbles' },
    { id: 'gov_int',    label: 'Gov.\nIntervention',          x: 275, y: 585, category: 'policy',     full: 'Government Intervention' },
    { id: 'gov_fail',   label: 'Gov.\nFailure',               x: 570, y: 585, category: 'policy',     full: 'Government Failure' },
  ],
  edges: [
    { from: 'scarcity',   to: 'ppf',        desc: 'Scarcity makes trade-offs visible \u2014 the PPF illustrates the opportunity cost of choosing more of one good' },
    { from: 'scarcity',   to: 'price_mech', desc: 'The price mechanism exists to solve the resource allocation problem that scarcity creates' },
    { from: 'scarcity',   to: 'spec',       desc: 'Scarcity incentivises specialisation to maximise efficiency from limited resources' },
    { from: 'ppf',        to: 'price_mech', desc: 'Opportunity cost underpins every price signal \u2014 prices reflect what must be sacrificed' },
    { from: 'price_mech', to: 'price_det',  desc: 'Price determination IS the mechanism in action \u2014 supply and demand converging on equilibrium' },
    { from: 'price_mech', to: 'mkt_fail',   desc: 'Market failure is definitionally a breakdown of the price mechanism \u2014 two sides of the same coin' },
    { from: 'cons_beh',   to: 'demand',     desc: 'Rational utility maximisation generates the downward-sloping demand curve via diminishing marginal utility' },
    { from: 'cons_beh',   to: 'info_fail',  desc: 'Irrational behaviour (herding, inertia, framing) is itself a key source of information failure' },
    { from: 'demand',     to: 'ped',        desc: 'PED measures responsiveness of Qd to price \u2014 it emerges directly from the demand curve\u2019s slope' },
    { from: 'demand',     to: 'price_det',  desc: 'Demand is one side of market equilibrium \u2014 shifts change equilibrium price and quantity' },
    { from: 'supply',     to: 'price_det',  desc: 'Supply is the other side \u2014 supply shifts change equilibrium price and quantity' },
    { from: 'supply',     to: 'pes',        desc: 'PES measures how responsive Qs is to price \u2014 determined by time, spare capacity, factor mobility' },
    { from: 'spec',       to: 'supply',     desc: 'Specialisation lowers unit costs via productivity gains \u2014 shifts the supply curve rightward' },
    { from: 'ped',        to: 'taxes',      desc: 'PED determines consumer burden of indirect tax \u2014 inelastic demand = consumers bear a larger share' },
    { from: 'pes',        to: 'taxes',      desc: 'PES determines producer burden \u2014 inelastic supply = producers bear a larger share of the tax' },
    { from: 'price_det',  to: 'surplus',    desc: 'Market equilibrium creates CS (area above P, below D) and PS \u2014 total welfare generated by the market' },
    { from: 'price_det',  to: 'taxes',      desc: 'Taxes shift supply left, subsidies shift right \u2014 both change price, quantity, and welfare' },
    { from: 'surplus',    to: 'gov_int',    desc: 'Welfare analysis (CS + PS) is the tool that judges whether intervention produces a net welfare gain' },
    { from: 'taxes',      to: 'mkt_fail',   desc: 'Pigouvian taxes equal to MEC are the primary tool to correct externality market failure' },
    { from: 'taxes',      to: 'gov_fail',   desc: 'A mis-set tax creates its own deadweight welfare loss \u2014 a major pathway to government failure' },
    { from: 'mkt_fail',   to: 'ext',        desc: 'Externalities (MSC \u2260 MPC, MSB \u2260 MPB) cause over/underproduction vs social optimum' },
    { from: 'mkt_fail',   to: 'pub_goods',  desc: 'Non-provision of public goods due to the free-rider problem is a source of market failure' },
    { from: 'mkt_fail',   to: 'info_fail',  desc: 'Imperfect/asymmetric information prevents rational decision-making \u2014 a key source of market failure' },
    { from: 'mkt_fail',   to: 'moral_haz',  desc: 'Moral hazard arises from information failure \u2014 protected agents take excessive risk as costs fall on others' },
    { from: 'mkt_fail',   to: 'bubbles',    desc: 'Speculation and bubbles represent a failure of rational pricing in financial and asset markets' },
    { from: 'mkt_fail',   to: 'gov_int',    desc: 'Market failure is the fundamental justification for all government intervention' },
    { from: 'ext',        to: 'gov_int',    desc: 'Externalities \u2192 Pigouvian taxes, subsidies, tradeable permits, regulation as corrective interventions' },
    { from: 'pub_goods',  to: 'gov_int',    desc: 'Public goods \u2192 state provision financed by taxation solves the free-rider problem' },
    { from: 'info_fail',  to: 'gov_int',    desc: 'Information failure \u2192 government campaigns, compulsory disclosure, regulation, consumer protection' },
    { from: 'gov_int',    to: 'gov_fail',   desc: 'Intervention can create a net welfare loss (government failure) via information gaps or unintended consequences' },
  ],
};

export const UNIT_2 = {
  viewBox: { w: 820, h: 595 },
  nodes: [
    { id: 'gdp',         label: 'Real GDP\n& Growth',       x: 120, y: 50,  category: 'measure',  full: 'Real GDP & Economic Growth' },
    { id: 'inflation',   label: 'Inflation\n(CPI)',         x: 275, y: 50,  category: 'measure',  full: 'Inflation & Deflation (CPI)' },
    { id: 'unemp',       label: 'Unemploy-\nment',          x: 440, y: 50,  category: 'measure',  full: 'Employment & Unemployment' },
    { id: 'bop',         label: 'Balance of\nPayments',     x: 615, y: 50,  category: 'measure',  full: 'Balance of Payments' },
    { id: 'cons',        label: 'Consump-\ntion (C)',       x: 80,  y: 150, category: 'ad',       full: 'Consumption (C)' },
    { id: 'invest',      label: 'Investment\n(I)',          x: 225, y: 150, category: 'ad',       full: 'Investment (I)' },
    { id: 'ad',          label: 'Aggregate\nDemand',        x: 420, y: 150, category: 'ad',       full: 'Aggregate Demand (AD)' },
    { id: 'gov_exp',     label: 'Gov. Exp.\n(G)',           x: 605, y: 150, category: 'ad',       full: 'Government Expenditure (G)' },
    { id: 'netx',        label: 'Net\nExports',             x: 755, y: 150, category: 'ad',       full: 'Net Exports (X-M)' },
    { id: 'sras',        label: 'SRAS',                     x: 210, y: 250, category: 'as',       full: 'Short-Run Aggregate Supply (SRAS)' },
    { id: 'lras',        label: 'LRAS',                     x: 420, y: 250, category: 'as',       full: 'Long-Run Aggregate Supply (LRAS)' },
    { id: 'mult',        label: 'Multiplier',               x: 645, y: 250, category: 'ad',       full: 'The Multiplier & Marginal Propensities' },
    { id: 'nat_inc',     label: 'National\nIncome',         x: 210, y: 345, category: 'income',   full: 'National Income & Circular Flow' },
    { id: 'growth',      label: 'Economic\nGrowth',         x: 420, y: 345, category: 'income',   full: 'Economic Growth (Actual vs Potential)' },
    { id: 'out_gap',     label: 'Output\nGaps',             x: 645, y: 345, category: 'income',   full: 'Output Gaps (Positive & Negative)' },
    { id: 'fiscal',      label: 'Fiscal\nPolicy',           x: 165, y: 450, category: 'policy',   full: 'Fiscal Policy (Spending & Taxation)' },
    { id: 'monetary',    label: 'Monetary\nPolicy',         x: 420, y: 450, category: 'policy',   full: 'Monetary Policy (Interest Rates, QE)' },
    { id: 'supply_side', label: 'Supply-Side\nPolicy',      x: 685, y: 450, category: 'policy',   full: 'Supply-Side Policies' },
    { id: 'objectives',  label: 'Macro\nObjectives',        x: 250, y: 540, category: 'conflict', full: 'Macroeconomic Objectives (all six)' },
    { id: 'phillips',    label: 'Phillips\nCurve',          x: 420, y: 540, category: 'conflict', full: 'The Phillips Curve (Inflation-Unemployment)' },
    { id: 'conflicts',   label: 'Policy\nConflicts',        x: 595, y: 540, category: 'conflict', full: 'Policy Conflicts & Trade-offs' },
  ],
  edges: [
    { from: 'gdp',         to: 'ad',          desc: 'Rising AD is the short-run cause of positive GDP growth \u2014 AD shifts right, output and GDP rise' },
    { from: 'inflation',   to: 'sras',        desc: 'Cost-push inflation is caused by SRAS shifting left (e.g. oil price rise) \u2014 links CPI to supply conditions' },
    { from: 'inflation',   to: 'monetary',    desc: 'Central banks use monetary policy (interest rate targeting) specifically to hit an inflation target' },
    { from: 'inflation',   to: 'phillips',    desc: 'Inflation is the vertical axis of the Phillips Curve \u2014 the core inflation-unemployment trade-off lives here' },
    { from: 'unemp',       to: 'ad',          desc: 'Demand-deficient unemployment falls when AD rises \u2014 firms hire more labour to meet higher demand' },
    { from: 'unemp',       to: 'supply_side', desc: 'Structural unemployment cannot be solved by demand management \u2014 it requires supply-side reform' },
    { from: 'unemp',       to: 'phillips',    desc: 'Unemployment is the horizontal axis of the Phillips Curve \u2014 the short-run trade-off with inflation' },
    { from: 'bop',         to: 'netx',        desc: 'The current account is largely determined by net exports (X-M) \u2014 the external component of AD' },
    { from: 'bop',         to: 'conflicts',   desc: 'BOP equilibrium conflicts with growth \u2014 more growth pulls in more imports, worsening the current account' },
    { from: 'cons',        to: 'ad',          desc: 'Consumption is the largest AD component (~65% of GDP) \u2014 the primary driver of AD shifts' },
    { from: 'invest',      to: 'ad',          desc: 'Investment is the most volatile AD component \u2014 highly sensitive to interest rates and confidence' },
    { from: 'gov_exp',     to: 'ad',          desc: 'Government expenditure is directly controlled by fiscal policy \u2014 changes in G directly shift AD' },
    { from: 'netx',        to: 'ad',          desc: 'Net exports connect the domestic economy to the global \u2014 exchange rates and foreign growth affect X-M' },
    { from: 'ad',          to: 'nat_inc',     desc: 'AD and AS together determine equilibrium national income \u2014 AD changes shift this equilibrium' },
    { from: 'ad',          to: 'mult',        desc: 'The multiplier amplifies AD shifts \u2014 an initial injection creates a larger total change in national income' },
    { from: 'ad',          to: 'out_gap',     desc: 'If AD rises above potential output, a positive output gap opens and inflationary pressure builds' },
    { from: 'sras',        to: 'nat_inc',     desc: 'In the short run, SRAS and AD together determine both the price level and real output' },
    { from: 'lras',        to: 'growth',      desc: 'A rightward LRAS shift is the only sustainable way to raise potential output permanently' },
    { from: 'lras',        to: 'out_gap',     desc: 'The output gap is measured relative to LRAS \u2014 actual output minus potential output' },
    { from: 'mult',        to: 'fiscal',      desc: 'The fiscal multiplier determines how effective government spending is \u2014 high MPM reduces its size' },
    { from: 'nat_inc',     to: 'growth',      desc: 'Economic growth is the rate of change in equilibrium real national income over time' },
    { from: 'growth',      to: 'objectives',  desc: 'Economic growth is one of the six macroeconomic objectives governments must pursue' },
    { from: 'out_gap',     to: 'fiscal',      desc: 'Negative output gap \u2192 expansionary fiscal policy; positive gap \u2192 contractionary to cool inflation' },
    { from: 'out_gap',     to: 'monetary',    desc: 'Output gaps guide central bank decisions \u2014 below potential = cut rates; above = raise rates' },
    { from: 'fiscal',      to: 'ad',          desc: 'Expansionary fiscal policy (raise G or cut taxes) directly shifts AD right \u2014 the primary demand-side tool' },
    { from: 'monetary',    to: 'invest',      desc: 'Lower interest rates reduce borrowing costs \u2192 investment becomes more profitable \u2192 I rises' },
    { from: 'monetary',    to: 'cons',        desc: 'Lower rates boost disposable income (mortgage holders) and consumer confidence \u2192 C rises' },
    { from: 'supply_side', to: 'lras',        desc: 'Supply-side policies (education, deregulation, infrastructure) shift LRAS right \u2014 raise productive capacity' },
    { from: 'fiscal',      to: 'objectives',  desc: 'Fiscal policy is one of the two primary instruments for pursuing macroeconomic objectives' },
    { from: 'monetary',    to: 'objectives',  desc: 'Monetary policy and inflation targeting is central to the price stability objective' },
    { from: 'objectives',  to: 'phillips',    desc: 'The Phillips Curve illustrates the core conflict between the inflation and unemployment objectives' },
    { from: 'objectives',  to: 'conflicts',   desc: 'The six objectives cannot all be maximised simultaneously \u2014 their conflicts are the key evaluation tool' },
    { from: 'phillips',    to: 'conflicts',   desc: 'The short-run Phillips Curve is the most important single conflict \u2014 lower unemployment = higher inflation' },
  ],
};

export const UNITS = {
  1: UNIT_1,
  2: UNIT_2,
};
